export function validateHTMLColor(input: string): boolean;
export function validateHTMLColorHex(input: string): boolean;
export function validateHTMLColorHsl(input: string): boolean;
export function validateHTMLColorName(input: string): boolean;
export function validateHTMLColorRgb(input: string): boolean;
export function validateHTMLColorSpecialName(input: string): boolean;
export function validateHTMLColorHwb(input: string): boolean;
export function validateHTMLColorLab(input: string): boolean;
export function validateHTMLColorLch(input: string): boolean;
export default function validateColor(input: string): boolean;
